### ISSUE TITLE
US 4.1 - Task2: Implement comments model backend

### ISSUE THREAD

**Issue by WW1027** [UB-ES-2024-B1/Software-Engineering#91]
Description: Develop the backend model to support comments in the forum. Implement features for creating, updating, and retrieving comments, along with validation for user input.

Backend member task: Create a model in order to save all the comments. The idea is creating a thread for each comment, and  programe a link between comment thread-movie-user. Finally the member needs to document the created model.

**Comment by Veroski** [comment]
Completed 😎🤠
